# Generated by Django 3.0.10 on 2021-05-24 01:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('Loyal Customers', 'Loyal Customers'), ('Impulse Shoppers', 'Impulse Shoppers'), ('Bargain Hunters', 'Bargain Hunters'), ('Wandering Consumers', 'Wandering Consumers'), ('Need-Based Customers', 'Need-Based Customers')], default='Loyal Customers', help_text='Consumer-based marketing', max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
