# Generated by Django 3.0.10 on 2021-03-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfiles',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
