# Generated by Django 3.0.10 on 2021-03-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210312_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_approved',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_pending',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_rejected',
        ),
        migrations.AddField(
            model_name='taskfiles',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
