# Generated by Django 3.0.10 on 2021-03-13 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210313_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_finished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
