# Generated by Django 3.0.10 on 2021-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210313_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approve_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Completed Overdue', 'Completed Overdue')], default='In Progress', max_length=25),
        ),
        migrations.AddField(
            model_name='task',
            name='upload_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Completed Overdue', 'Completed Overdue')], default='In Progress', max_length=25),
        ),
    ]
