# Generated by Django 3.0.10 on 2021-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210313_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfiles',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
